postgres:
    image: postgres
    environment:
        - POSTGRES_USER=airflow
        - POSTGRES_PASSWORD=airflow
        - POSTGRES_DB=airflow

rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
        - "15672:15672"
        - "5672:5672"
    environment:
        - RABBITMQ_DEFAULT_USER=airflow
        - RABBITMQ_DEFAULT_PASS=airflow
        - RABBITMQ_DEFAULT_VHOST=airflow

webserver:
    image: flolas/docker-airflow
    restart: always
    # volumes:
    #     - /localpath/to/dags:/usr/local/airflow/dags
    environment:
        - AIRFLOW_HOME=/usr/local/airflow
    ports:
        - "8088:8080"
    links:
        - postgres:postgres
        - rabbitmq:rabbitmq
        - worker:worker
        - scheduler:scheduler
    command: webserver

flower:
    image: flolas/docker-airflow
    restart: always
    environment:
        - AIRFLOW_HOME=/usr/local/airflow
    ports:
        - "5555:5555"
    links:
        - rabbitmq:rabbitmq
    command: flower

scheduler:
    image: flolas/docker-airflow
    restart: always
    volumes:
        - /opt/dags:/usr/local/airflow/dags
    environment:
        - AIRFLOW_HOME=/usr/local/airflow
    links:
        - postgres:postgres
        - rabbitmq:rabbitmq
    command: scheduler -n 5

worker:
    image: flolas/docker-airflow
    restart: always
    volumes:
        - /opt/dags:/usr/local/airflow/dags
    environment:
        - AIRFLOW_HOME=/usr/local/airflow
    links:
        - postgres:postgres
        - rabbitmq:rabbitmq
    command: worker
