SELECT * FROM financial.trans;
SELECT * FROM financial.prueba_final2;
SELECT * FROM financial.prueba_final2;
SELECT * FROM financial.prueba_final2;
SELECT * FROM financial.prueba_final2;
SELECT * FROM financial.prueba_final2;
SELECT * FROM financial.prueba_final2;
SELECT * FROM financial.prueba_final2;
SELECT COUNT(*) FROM financial.trans;